apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  containers:
  - name: nodejs-app
    image: uphiller/nodejs-hello-world:configmap
    ports:
    - containerPort: 3000
    env:
    - name: LANGUAGE
      valueFrom:
        secretKeyRef:
          name: hello-secret
          key: language

