apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  containers:
  - name: nodejs-app
    image: uphiller/nodejs-hello-world:configmap
    ports:
    - containerPort: 3000
    env:
    - name: LANGUAGE
      valueFrom:
        secretKeyRef:
          name: hello-secret
          key: language
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000

