apiVersion: v1
kind: Pod
metadata:
  name: board-app-backend
  labels:
    app: board-app-backend
    group: board
spec:
  containers:
  - name: backend
    image: uphiller/board-backend
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 168.126.63.1
    searches:
    - example.co.kr
    - abc.co.kr  
    options:
    - name: name01
      value: value01
    - name: name02
