apiVersion: v1
kind: Pod
metadata:
  name: board-app-front
  labels:
    app: board-app-front
    group: board
spec:
  containers:
  - name: front
    image: uphiller/board-front
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 168.126.63.1
    searches:
    - example.co.kr
    - abc.co.kr  
    options:
    - name: name01
      value: value01
    - name: name02

