apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: board-app
      labels:
        app: board-app 
    spec:
      containers:
      - name: backend 
        image: uphiller/board-backend:local
        ports:
        - containerPort: 8080
      - name: front
        image: uphiller/board-front
        ports:
        - containerPort: 80    
      - name: mysql 
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
  - apiVersion: v1
    kind: Service
    metadata:
      name: board-front
    spec:
      type: NodePort
      selector:
        app: board-app
      ports:
      - port: 80
        protocol: TCP
        targetPort: 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: board-backend
    spec:
      type: NodePort
      selector:
        app: board-app
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
